config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'persons/profile'

  namespace :metadata do
    resources :categories do
      get 'add_existed'
      get 'remove_link'
      resources :categories
      get 'parent_params'
      put 'update_category_property_position', on: :collection

      resources :properties do
        resources :category_properties
        resources :list_items
        resources :hierarch_list_items do
          resources :hierarch_list_items
        end
      end
    end

    root to: 'categories#index'
  end

  resources :users
  namespace :my do
    resources :adverts do
      get 'get_category_children', on: :collection
    end

    root to: 'adverts#index'
  end

  resources :categories do
    get 'get_hierarch_children', on: :collection
  end

  resources :adverts
  root to: 'categories#index'
end

app/models/category.rb
class Category < ActiveRecord::Base
  belongs_to :link, foreign_key: 'connect_with_id', class_name: 'Category'

  has_many :links, foreign_key: 'connect_with_id', class_name: 'Category'
  has_many :adverts, dependent: :destroy
  has_many :category_properties, dependent: :destroy
  has_many :properties, through: :category_properties
  has_many :old_properties, foreign_key: 'category_id', class_name: 'Property'

  validates_presence_of :title

  accepts_nested_attributes_for :properties

  has_ancestry cache_depth: true

  alias_attribute :to_s, :title

  scope :ordered, -> {order('title')}
  scope :not_connected, -> {where(:connect_with_id == nil)}
  scope :connected, -> {where(:connect_with_id != nil)}

  #searchable  do
    #text :title
  #end

  def all_properties
    [].tap do |array|
      properties.each do |property|
        if ["limited_list", "unlimited_list", "hierarch_limited_list"].include? property.kind
          array << property
        end
      end
    end
  end

  def inserted
    links.flatten + children.flatten
  end
end

# == Schema Information
#
# Table name: categories
#
#  id              :integer          not null, primary key
#  title           :string
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  ancestry        :string
#  ancestry_depth  :integer          default(0)
#  connect_with_id :integer
#

app/controllers/categories_controller.rb
# == Schema Information
#
# Table name: categories
#
#  id              :integer          not null, primary key
#  title           :string
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  ancestry        :string
#  ancestry_depth  :integer          default(0)
#  connect_with_id :integer
#

class CategoriesController < ApplicationController
  include Breadcrumbs

  def index
    @categories = Category.roots
  end

  def show
    @category = Category.find(params[:id])
    @adverts = Searchers::AdvertsSearcher.new(adverts_search_params).collection




    #raise adverts_search_params.inspect
    initialize_breadcrumbs
  end

  def initialize_breadcrumbs
    breadcrumbs_create(@category)
    add_breadcrumb  @category
  end

  def get_hierarch_children
    if request.xhr?
      array = []
      HierarchListItem.find(params[:parent_id]).children.each do |child|
        h = {}
        h[:id] = child.id
        h[:title] = child.title

        array << h
      end
      render text: array.to_json and return
    end
  end

  private
  def adverts_search_params
    #raise params.inspect
    param_lists = params.try(:[], :list_items)
    ranges_values = params.try(:[], :ranges)
    ranges_select_values = params.try(:[], :ranges_select)

    if !ranges_values.nil?
      elems = []
      ranges_values.each do |p|
        values = p[1].split(',').map(&:to_i)
        elems << @category.properties.find(p[0].to_i).list_items.select {|l| l.title.to_i >= values[0] && l.title.to_i <= values[1]}.map(&:id).map(&:to_s) if values.size == 2
      end
      param_lists << elems
      param_lists = param_lists.flatten
    end

    if !ranges_select_values.nil?
      elems = []
      values = []
      ranges_select_values.each do |p|

        if p[1][0] != ""
          values[0] = ListItem.find(p[1][0].to_i).title.to_i
        else
          values[0] = @category.properties.find(p[0]).list_items.first.title.to_i
        end

        if p[1][1] != ""
          values[1] = ListItem.find(p[1][1].to_i).title.to_i
        else
          values[1] = @category.properties.find(p[0]).list_items.last.title.to_i
        end

        values.sort!
        elems << @category.properties.find(p[0].to_i).list_items.select {|l| l.title.to_i >= values[0] && l.title.to_i <= values[1]}.map(&:id).map(&:to_s) if values.size == 2
      end
      param_lists << elems
      param_lists = param_lists.flatten
    end

    {
      list_items: param_lists,
      hierarch_list_items: params.try(:[], :hierarch_list_items),
      category_id: @category.id,
      page: params[:page]
    }
  end
end

app/controllers/metadata/application_controller.rb
class Metadata::ApplicationController < ApplicationController
  load_and_authorize_resource

  protect_from_forgery with: :exception

  before_action :authenticate_user!

  layout :resolve_layout

  def current_ability
    Ability.new(current_user, :metadata)
  end

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_url, :alert => exception.message
  end

  def resolve_layout
    request.xhr? ? false : 'metadata'
  end
end

app/controllers/metadata/categories_controller.rb
class Metadata::CategoriesController < Metadata::ApplicationController
  before_action :find_category, only: [:show, :edit, :destroy]

  def index
    @categories = Category.roots.ordered
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      render partial: 'children', locals: { category: @category.parent } and return if request.xhr?

      respond_with @category, location: -> { [:metadata, @category] }
    else
      render :new and return
    end
  end

  def edit
  end

  def show
  end

  def update
    if @category.update(category_params)
      render partial: 'children', locals: { category: @category.parent } and return if request.xhr?

      respond_with @category, location: -> { [:metadata, @category] }
    else
      render :edit and return
    end
  end

  def add_existed
    @category = Category.find(params[:category_id])
    @categories = Category.roots.ordered
  end

  def remove_link
    Category.find(params[:category_id]).update_column(:connect_with_id,  nil)

    render partial: 'children', locals: { category: Category.find(params[:parent_id]) } and return
  end

  def destroy
    if @category.parent
      @parent = @category.parent
      @category.destroy
      render partial: 'children', locals: { category: @parent } and return if request.xhr?
    else
      @category.destroy
      redirect_to metadata_categories_path
    end
  end

  def update_category_property_position
    CategoryProperty.find(params[:category_property_id]).update_attribute :row_order_position, params[:row_order]

    render nothing: true and return
  end

  private
  def category_params
    params.require(:category).permit(:title, :parent_id, property_ids: [], link_ids: [])
  end

  def find_category
    @category = Category.find(params[:id])
  end
end

app/controllers/metadata/category_properties_controller.rb
class Metadata::CategoryPropertiesController < ApplicationController
  before_action :find_category
  before_action :find_category_property, only: [:edit]

  def new
    @caregory_property = CategoryProperty.create(:category_id => params[:category_id], :property_id => params[:property_id],
                                                 :necessarily => params[:necessarily],
                                                 :show_as => params[:show_as],
                                                 :show_on_public => params[:show_on_public])
    redirect_to metadata_category_path(@category)
  end

  def edit
    @category_property.update(:category_id => params[:category_id], :property_id => params[:property_id],
                              :necessarily => params[:necessarily],
                              :show_as => params[:show_as],
                              :show_on_public => params[:show_on_public])

    redirect_to metadata_category_path(@category)
  end

  def find_category_property
    @category_property = CategoryProperty.find(params[:id])
  end

  def find_category
    @category = Category.find(params[:category_id])
  end
end

app/controllers/metadata/hierarch_list_items_controller.rb
class Metadata::HierarchListItemsController < ApplicationController
  before_action :find_category
  before_action :find_property
  before_action :find_hierarch_list_item, only: [:show, :edit, :update, :destroy]
  before_action :find_parent_item, only: [:create]

  def new
    @hierarch_list_item = if params[:parent_id]
                            HierarchListItem.find(params[:parent_id]).children.new
                          else
                            HierarchListItem.new
                          end
  end

  def create
    @hierarch_list_item = if params[:parent_id]
                            @parent_item.children.create(hierarch_list_item_params)
                          else
                            HierarchListItem.create(hierarch_list_item_params)
                          end

    respond_with @hierarch_list_item,
      location: -> { [:metadata, @category, @property, @hierarch_list_item.parent.presence || @hierarch_list_item]}
  end

  def find_category
    @category = Category.find(params[:category_id])
  end

  def find_property
    @property = Property.find(params[:property_id])
  end

  def find_parent_item
    if params[:parent_id]
      @parent_item = HierarchListItem.find(params[:parent_id])
    end
  end

  private
  def find_hierarch_list_item
    @hierarch_list_item = HierarchListItem.find(params[:id])
  end

  def hierarch_list_item_params
    params.require(:hierarch_list_item).permit(:title, :parent_id, :property_id)
  end
end

app/controllers/metadata/list_items_controller.rb
class Metadata::ListItemsController < Metadata::ApplicationController
end

app/controllers/metadata/properties_controller.rb
class Metadata::PropertiesController < Metadata::ApplicationController
  before_action :find_category
  before_action :find_property, only: [:edit, :update, :destroy]
  before_action :find_category_property, only: [:edit, :update, :destroy]

  def new
    @property = Property.new property_params
    @category_property = CategoryProperty.new
    @collection_for_filter = determinate_collection_for_filter
  end

  def determinate_collection_for_filter
    case @property.kind.to_s
    when "string"
      []
    when "limited_list"
      [:select, :check_boxes, :range, :multiselect, :radio_buttons, :boolean, :range_buttons, :range_select]
    when "unlimited_list"
      [:select, :check_boxes, :range, :multiselect, :radio_buttons, :boolean, :range_buttons, :range_select]
    when "hierarch_limited_list"
      [:boolean]
    when "integer"
      [:check_boxes, :range, :range_buttons, :range_select]
    when "float"
      [:check_boxes, :range, :range_buttons, :range_select]
    when "boolean"
      [:boolean]
    end
  end


  def create
    @property = Property.create property_params

    respond_with @property,
      location: -> { new_metadata_category_property_category_property_path(@category, @property, :params => category_property_params) }
  end

  def edit
    @collection_for_filter = determinate_collection_for_filter
  end

  def update
    @property.update(property_params)

    respond_with @property,
      location: -> { edit_metadata_category_property_category_property_path(@category, @property, @category_property, :params => category_property_params) }
  end

  def destroy
    @category_property.destroy

    respond_with @property, location: -> { metadata_category_path(@category)  }
  end

  private
  def find_property
    @property = @category.properties.find(params[:id])
  end

  def property_params
    params.
      require(:property).
      permit(:title, :kind, :category_id, :show_on_filter_as,
             hierarch_list_items_attributes: [:id, :title, :_destroy],
             list_items_attributes: [:id, :title, :_destroy])
  end

  def category_property_params
    params.
      require(:property).require(:category_property).
      permit(:show_on_public, :show_as, :necessarily, :category_id)
  end

  def find_category
    @category = Category.find(params[:category_id])
  end

  def find_category_property
    @category_property = CategoryProperty.where(:category_id => @category, :property_id => @property).first
  end
end

app/helpers/categories_helper.rb
# == Schema Information
#
# Table name: categories
#
#  id              :integer          not null, primary key
#  title           :string
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  ancestry        :string
#  ancestry_depth  :integer          default(0)
#  connect_with_id :integer
#

module CategoriesHelper
  def min_value(property)
    property.list_items.map(&:title).map(&:to_i).delete_if {|x| x == 0}.min
  end
  def max_value(property)
    property.list_items.map(&:title).map(&:to_i).max
  end
  def ticks_value(property)
    property.list_items.map(&:title).map(&:to_i).delete_if{|x| x == 0}.sort.each_slice(property.list_items.count/4).map(&:first)
  end
  def value(property_id, params_ranges)
    if !params_ranges.nil?
      params_ranges.find {|p| p[0].to_i == property_id}[1].split(',').map(&:to_i)
    else
      property = Property.find(property_id)
      return [min_value(property),max_value(property)]
    end
  end
  def selected_for_ranges_select(params_ranges_select, property, position)
    if !params_ranges_select.try(:[], "#{property.id.to_s}").nil?
      params_ranges_select[property.id.to_s][position == 'first' ? 0 : 1]
    end
  end
end

app/helpers/metadata/categories_helper.rb
module Metadata::CategoriesHelper
  def recursive_children(node)
    return '' unless node.inserted.present?

    # FIXME: странно, но с нормальными content_tag сходу не заработало. пока так, надо переписать

    content = '<ul class="js-can-hidden can-hidden">'
    node.inserted.each do |child|
      content << "<li>#{link_to child, metadata_category_category_path(node, child)}"
      content << "<span class='glyphicon glyphicon-plus js-handle-hidden'></span>" if child.inserted.present?

      content << recursive_children(child) if child.inserted.present?
      content << "</li>"
    end
    content << '</ul>'

    content.html_safe
  end

  def define_remote(params)
    if params[:remote].present?
      params[:remote] == 'true' ? true : false

      return
    end

    true
  end
end

app/helpers/metadata/category_properties_helper.rb
module Metadata::CategoryPropertiesHelper
end

app/helpers/metadata/hierarch_list_items_helper.rb
module Metadata::HierarchListItemsHelper
end

app/helpers/metadata/properties_helper.rb
module Metadata::PropertiesHelper
  def can_change_property_fields?(category, property)
    category.is_root? || property.new_record? || CategoryProperty.where(:property_id => property.id).sort.first.category == category
  end
end

app/views/metadata/categories/_add_property.html.haml
%h4= 'Добавление нового аттрибута'
= simple_form_for :property, url: new_metadata_category_property_path(@category), method: :get do |f|
  = f.input :kind, as: :select, collection: Property.kind.options, include_blank: true, selected: nil, input_html: { class: 'js-properties-types' }

  = f.submit 'Добавить', class: 'btn btn-success'

app/views/metadata/categories/_children.html.haml
- category.children.each do |child|
  %li{data: {id: child.id}, class: "js-child"}= "#{link_to child, metadata_category_category_path(category, child)} | #{link_to 'Редактировать', edit_metadata_category_category_path(category, child), class: "js-link-to-edit", :"data-id" => child.id,  remote: true} | #{link_to 'Удалить', metadata_category_category_path(category, child), data: {confirm: 'Вы уверены?'}, class: "js-link-to-destroy", remote: true, method: :delete}".html_safe
- category.links.each do |child|
  %li{data: {id: child.id}, class: "js-child"}= "#{link_to child, metadata_category_category_path(category, child)} | #{link_to 'Отключить', metadata_category_remove_link_path(child, :parent_id => category), data: {confirm: 'Вы уверены?'}, class: "js-link-to-destroy", remote: true} (Ссылка #{child.parent if child.parent.present?})".html_safe

app/views/metadata/categories/_form.html.haml
= simple_nested_form_for [:metadata, @category], remote: define_remote(params) do |f|
  = f.input :title
  = f.input :parent_id, input_html: { value: params[:parent_id]}, as: :hidden  if params[:parent_id]
  = f.input :parent_id, input_html: { value: params[:category][:parent_id]}, as: :hidden  if params[:category]
  = f.input :parent_id, input_html: { value: params[:category_id]}, as: :hidden  if params[:category_id]
  = f.submit

app/views/metadata/categories/_parent.html.haml
- if parents.present?
  - parents.each do |category|
    .row
      .col-xs-9
        %p= link_to category, metadata_category_path(category)

app/views/metadata/categories/_recursive_children.html.haml
%ul.js-can-hidden.can-hidden
  - category.children.each do |child|
    %li
      = f.input :link_ids,
        as: :check_boxes,
        collection: [child],
        :disabled => (child != current_category && !current_category.children.try(:include?, child) && !current_category.try(:ancestors).try(:include?, child) && !current_category.try(:link).try(:ancestors).try(:include?, child) && child != current_category.link) ? false : true,
        label: false
      - if child.link.present?
        = "(Прикреплён к #{ child.link })"
      - if child.children.present?
        %span.glyphicon.glyphicon-plus.js-handle-hidden
        = render partial: 'recursive_children', locals: { :f => f, :category => child, :current_category => current_category }

app/views/metadata/categories/add_existed.html.haml
.row
  .col-xs-10
    %h1= "Выберите категорию"
    = simple_nested_form_for [:metadata, @category] do |f|
      %ul
        - @categories.each do |category|
          %li
            = f.input :link_ids,
              as: :check_boxes,
              collection: [category],
              :disabled => (category != @category && !@category.children.try(:include?, category) && !@category.ancestors.try(:include?, category) && !@category.link.try(:ancestors).try(:include?, category) && category != @category.link) ? false : true,
              label: false
            - if category.link.present?
              = "(Прикреплён к #{category.link})"
            %span.glyphicon.glyphicon-plus.js-handle-hidden
            = render partial: 'recursive_children', locals: { :f => f, :category => category, :current_category => @category }

      = f.submit




%br

app/views/metadata/categories/add_parent_params.html.haml
= simple_nested_form_for [:metadata, @category] do |f|
  = f.input :property_ids,
    as: :check_boxes,
    collection: @properties
  = f.submit

app/views/metadata/categories/edit.html.haml
= render partial: 'form'
- if params[:remote] == 'false'
  %p= link_to 'Вернуться', metadata_category_path(@category)

app/views/metadata/categories/index.html.haml
.row
  .col-xs-10
    %h1='Управление категориями'

    %h3='Категории'
    %ul
      - @categories.each do |category|
        %li
          = link_to category, metadata_category_path(category)
          %span.glyphicon.glyphicon-plus.js-handle-hidden
          = recursive_children(category)
    %p= link_to 'Главная страница', root_path

  .col-xs-2
    = link_to t('categories.new'), new_metadata_category_path(remote: false), class: 'btn btn-default'

app/views/metadata/categories/new.html.haml
= render partial: 'form'
- if params[:remote] == 'false'
  %p= link_to 'Отмена', metadata_categories_path

app/views/metadata/categories/parent_params.html.haml
- @category_properties = (@category.ancestors.map(&:category_properties).flatten + @category.category_properties).uniq
= simple_nested_form_for [:metadata, @category] do |f|
  = f.input :property_ids,
    as: :check_boxes,
    collection: @category_properties.map(&:property).flatten.uniq,
    :label_method => lambda { |item| "#{item}  (#{@category_properties.select{|cp| cp.property == item}.first.category.title})".html_safe }
  = f.submit

app/views/metadata/categories/show.html.haml
%h4= 'Родительские категории'
= render partial: 'parent', collection: [@category.ancestors], as: :parents

- if @category.link
  %h4= "Подключена к"
  =link_to @category.link, metadata_category_path(@category.link)

.row
  .col-xs-9
    %h4='Категория'
    %h2= @category

  .col-xs-3
    %p= "#{link_to 'Редактировать', edit_metadata_category_path(@category, remote: false)} | #{link_to 'Удалить', metadata_category_path(@category), method: :delete, data: { confirm: 'Вы уверены?' }} | #{link_to 'Вернуться', metadata_categories_path}".html_safe

.row
  .col-xs-6
    %h4='Аттрибуты'
    %ul.js-sortable-wrapper{data: { path: update_category_property_position_metadata_categories_path  }}
      - @category.properties.each do |property|
        %li.js-sortable-item{data: { id: @category.category_properties.where(:property_id => property.id).first.id }}= "#{link_to property, metadata_category_property_path(@category, property)} | #{link_to 'Редактировать', edit_metadata_category_property_path(@category, property) } | #{link_to 'Удалить аттрибут', metadata_category_property_path(@category, property), method: :delete, data: { confirm: 'Вы уверены?' }} (#{property.kind_text}) <span class='glyphicon glyphicon-resize-vertical js-handle-sortable sortable' aria-hidden='true'></span>".html_safe
    - unless @category.has_children?
      =link_to 'Управление атрибутами', metadata_category_parent_params_path(@category, id: @category)


    .categories.js-categories
      %h4='Вложенные категории'

      %ul.js-children
        = render partial: 'children', locals: { category: @category }

      .dialog.js-dialog-to-add
      .js-link-to-edit
      .js-link-to-destroy
      .js-link-to-add
        =link_to 'Добавить вложенную категорию', new_metadata_category_category_path(@category, parent_id: params[:id]), remote: true
      %hr
      .js-link-to-add-existed
        =link_to 'Добавить существующую категорию', metadata_category_add_existed_path(@category)


  .col-xs-6
    %h4='Добавление нового аттрибута'
    = simple_form_for :property, url: new_metadata_category_property_path(@category), method: :get do |f|
      = f.input :kind, as: :select, collection: Property.kind.options, include_blank: true, selected: nil, input_html: { class: 'js-properties-types' }

      = f.submit 'Добавить', class: 'btn btn-success'