config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'persons/profile'

  namespace :metadata do
    resources :categories do
      get 'add_existed'
      get 'remove_link'
      resources :categories
      get 'parent_params'
      put 'update_category_property_position', on: :collection

      resources :properties do
        resources :category_properties
        resources :list_items
        resources :hierarch_list_items do
          resources :hierarch_list_items
        end
      end
    end

    root to: 'categories#index'
  end

  resources :users
  namespace :my do
    resources :adverts do
      get 'get_category_children', on: :collection
    end

    root to: 'adverts#index'
  end

  resources :categories do
    get 'get_hierarch_children', on: :collection
  end

  resources :adverts
  root to: 'categories#index'
end

app/models/advert.rb
class Advert < ActiveRecord::Base
  after_save :set_title
  belongs_to :category
  belongs_to :user

  has_many :values, dependent: :delete_all
  has_many :images, dependent: :destroy
  accepts_nested_attributes_for :values
  accepts_nested_attributes_for :images, allow_destroy: true

  after_initialize :build_empty_values, if: :new_record?

  alias_attribute :to_s, :title

  def title
    $redis.get(id)
  end

  def set_title
    string_title = ''
    if category.title ==  "Легковые автомобили"
      string_title = get_value_hierarch('марка и модель', false) +
        get_value('год', false) +
        get_value('пробег', true) +
        get_value('мощность', true) +
        get_value('кузов', true) +
        get_value('привод', true)
    elsif category.root.id == 338 #вся недвижимость
      string_title = get_value('комнат', true) +
        get_value('площадь', false) +
        get_value('этажей', true) +
        get_value('страна', false)
    end
    if string_title == ''
      values.each do |value|
        string_title += get_value(value.property, true)
      end
    end
    string_title = read_attribute(:description) if string_title == ''
    $redis.set(id, string_title.strip.chomp(','))
  end

  def get_value(property_title, need_prefix)
    property_finded = category.properties.where('title ilike ?', "%#{property_title}%").first
    return '' if property_finded.nil? || property_finded.kind == 'unlimited_list'
    string_value = property_finded.values.where(:advert_id => id).find { |v| v if v.value != nil }.try(:value).try(:to_s)
    if !string_value.nil?
      string_value += ', '
      string_value = property_finded.title + ': ' + string_value if need_prefix
    else
      string_value = ''
    end
    string_value
  end

  def get_value_hierarch(property_title, need_prefix)
    property_finded = category.properties.where('title ilike ?', "%#{property_title}%").first
    return '' if property_finded.nil?
    lists = property_finded.values.where(:advert_id => id).find {|v| v if v.hierarch_list_item != nil}.try(:hierarch_list_item).try(:path).try(:to_a)
    if lists.try(:size) == 2
      string_value = lists[0].title + ' ' + lists[1].title + ', '
      string_value = property_finded.title + ': ' + string_value if need_prefix
    else
      string_value = ''
    end
    string_value
  end

  private
  def build_empty_values
    return unless category

    category.properties.each do |property|
      values << property.values.new unless values.select {|v| v.property == property}.any?
    end
  end

  searchable include: [:values] do
    integer :list_item_ids, multiple: true do
      values.map { |v| v.list_items.map(&:id) + values.map(&:list_item).compact.map(&:id) }.flatten.compact.uniq
    end

    integer :hierarch_list_item_ids, multiple: true do
      values.map(&:hierarch_list_item).compact.map(&:id)
    end

    integer(:category_id) { category.id }
  end
end

# == Schema Information
#
# Table name: adverts
#
#  id          :integer          not null, primary key
#  description :text
#  category_id :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  user_id     :integer
#

app/controllers/adverts_controller.rb
# == Schema Information
#
# Table name: adverts
#
#  id          :integer          not null, primary key
#  description :text
#  category_id :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  user_id     :integer
#

class AdvertsController < ApplicationController
  include Breadcrumbs
  def show
    @advert = Advert.find(params[:id])
    initialize_breadcrumbs
  end

  def initialize_breadcrumbs
    breadcrumbs_create(@advert.category)
    add_breadcrumb @advert.category, category_path(@advert.category)
    add_breadcrumb @advert
  end
end

app/controllers/my/adverts_controller.rb
class My::AdvertsController < My::ApplicationController
  include Breadcrumbs

  before_action :find_category, only: [:new, :create]
  before_action :find_advert, only: [:show, :edit, :update, :destroy]

  def index
    @adverts = current_user.adverts
  end

  def new
    if @category
      if @category.inserted.present?
        @categories = @category.inserted
      else
        @advert = @category.adverts.build
      end
    else
      @categories = Category.roots.ordered
    end
  end

  def create
    @advert = @category.adverts.new(advert_params)

    if @advert.save
      respond_with @advert, location: -> { [:my, @advert] }
    else
      @advert.valid?
      render :new and return
    end
  end

  def edit
  end

  def show
  end

  def update
    @advert.update(advert_params)

    respond_with @advert, location: -> { [:my, @advert] }
  end

  def destroy
    @advert.destroy

    respond_with @advert, location: -> { my_adverts_path }
  end

  def get_category_children
    if request.xhr?
      array = []
      HierarchListItem.find(params[:parent_id]).children.each do |child|
        h = {}
        h[:id] = child.id
        h[:title] = child.title

        array << h
      end

      render text: array.to_json and return
    end
  end

  private
  def advert_params
    params.
      require(:advert).
      permit(:description, :category_id, :user_id,
             values_attributes: [:string_value, :integer_value, :float_value,
                                 :property_id, :id,
                                 :boolean_value,
                                 :list_item_id,
                                 :hierarch_list_item_id,
                                 :category_id,
                                 list_item_ids: []],
              images_attributes: [:id, :image, :_destroy]
            )
  end

  def find_advert
    @advert = Advert.find(params[:id])
  end

  def find_category
    @category = Category.find_by_id(params[:category_id] || params[:advert].try(:[], :category_id))
  end

  def initialize_breadcrumbs
    breadcrumbs_create(@advert.category)
    add_breadcrumb @advert.category, category_path(@advert.category)
    add_breadcrumb @advert
  end
end

app/controllers/my/application_controller.rb
class My::ApplicationController < ApplicationController
  before_action :authenticate_user!

  load_and_authorize_resource

  layout 'my'

  def current_ability
    Ability.new(current_user, :my)
  end

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_url, :alert => exception.message
  end
end

app/helpers/my/adverts_helper.rb
module My::AdvertsHelper
  def property_show_as(value, category_id)
    CategoryProperty.find_by(category_id: category_id, property_id: value.property).show_as.to_sym
  end
end

app/views/my/adverts/_form.html.haml
= simple_nested_form_for [:my, @advert] do |f|
  = f.input :category_id, as: :hidden
  = f.input :user_id, input_html: { value: current_user.id }, as: :hidden

  = f.simple_fields_for :values do |value_form|
    = value_form.input :property_id, as: :hidden
    = value_form.input :category_id, as: :hidden, input_html: { value: @advert.category.id }

    = render partial: "my/values_fields/#{value_form.object.property.kind}", locals: { f: value_form }
    - value_form.object.errors.full_messages.each do |msg|
      %span{:class => "help-block"}= msg

  %h4= 'Изображения'
  .js-images
    = f.simple_fields_for :images do |i|
      .js-image
        = image_tag i.object.image.url(:thumb)
        = i.file_field :image, style: 'display:none', class: 'js-file-input'
        = i.link_to_remove 'Удалить'
    = f.link_to_add 'Добавить картинку', :images

  = f.input :description # Стандартное описание объявления

  = f.submit

app/views/my/adverts/_values.html.haml
-#= f.simple_fields_for :values do |value_form|
  = value_form.input :property_id, as: :hidden
  = value_form.input :id, as: :hidden
  = render partial: "my/values_fields/#{value_form.object.property.kind}", locals: {:f => value_form}

app/views/my/adverts/edit.html.haml
= render partial: 'form'

app/views/my/adverts/index.html.haml
- @adverts.each do |advert|
  %p= link_to "#{advert.category.title} #{advert.title}", [:my, advert]
= link_to t('adverts.new'), new_my_advert_path
%p= link_to 'Главная страница', root_path

app/views/my/adverts/new.html.haml
%p= render_breadcrumbs

- if @categories
  %h3= t('categories.choose')
  - @categories.each do |category|
    %p= link_to category, [:new, :my, :advert, category_id: category]
- else # @advert.presence
  = render partial: 'form'

app/views/my/adverts/show.html.haml
- @advert.values.each do |value|
  = render partial: "common/values/#{value.property.kind}", locals: {:value => value}

  %hr

- @advert.images.each do |i|
  = render partial: "common/values/image", locals: {:image => i}

%p= @advert.description
%p= link_to 'Редактировать', edit_my_advert_path(@advert)
%p= link_to 'Удалить', my_advert_path(@advert), method: :delete, data: { confirm: 'Вы уверены?' }
%p= link_to 'Мои объявления', my_adverts_path