config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'persons/profile'

  namespace :metadata do
    resources :categories do
      get 'add_existed'
      get 'remove_link'
      resources :categories
      get 'parent_params'
      put 'update_category_property_position', on: :collection

      resources :properties do
        resources :category_properties
        resources :list_items
        resources :hierarch_list_items do
          resources :hierarch_list_items
        end
      end
    end

    root to: 'categories#index'
  end

  resources :users
  namespace :my do
    resources :adverts do
      get 'get_category_children', on: :collection
    end

    root to: 'adverts#index'
  end

  resources :categories do
    get 'get_hierarch_children', on: :collection
  end

  resources :adverts
  root to: 'categories#index'
end

app/models/category.rb
class Category < ActiveRecord::Base
  belongs_to :link, foreign_key: 'connect_with_id', class_name: 'Category'

  has_many :links, foreign_key: 'connect_with_id', class_name: 'Category'
  has_many :adverts, dependent: :destroy
  has_many :category_properties, dependent: :destroy
  has_many :properties, through: :category_properties
  has_many :old_properties, foreign_key: 'category_id', class_name: 'Property'

  validates_presence_of :title

  accepts_nested_attributes_for :properties

  has_ancestry cache_depth: true

  alias_attribute :to_s, :title

  scope :ordered, -> {order('title')}
  scope :not_connected, -> {where(:connect_with_id == nil)}
  scope :connected, -> {where(:connect_with_id != nil)}

  #searchable  do
    #text :title
  #end

  def all_properties
    [].tap do |array|
      properties.each do |property|
        if ["limited_list", "unlimited_list", "hierarch_limited_list"].include? property.kind
          array << property
        end
      end
    end
  end

  def inserted
    links.flatten + children.flatten
  end
end

# == Schema Information
#
# Table name: categories
#
#  id              :integer          not null, primary key
#  title           :string
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  ancestry        :string
#  ancestry_depth  :integer          default(0)
#  connect_with_id :integer
#

app/controllers/categories_controller.rb
# == Schema Information
#
# Table name: categories
#
#  id              :integer          not null, primary key
#  title           :string
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  ancestry        :string
#  ancestry_depth  :integer          default(0)
#  connect_with_id :integer
#

class CategoriesController < ApplicationController
  include Breadcrumbs

  def index
    @categories = Category.roots
  end

  def show
    @category = Category.find(params[:id])
    @adverts = Searchers::AdvertsSearcher.new(adverts_search_params).collection




    #raise adverts_search_params.inspect
    initialize_breadcrumbs
  end

  def initialize_breadcrumbs
    breadcrumbs_create(@category)
    add_breadcrumb  @category
  end

  def get_hierarch_children
    if request.xhr?
      array = []
      HierarchListItem.find(params[:parent_id]).children.each do |child|
        h = {}
        h[:id] = child.id
        h[:title] = child.title

        array << h
      end
      render text: array.to_json and return
    end
  end

  private
  def adverts_search_params
    #raise params.inspect
    param_lists = params.try(:[], :list_items)
    ranges_values = params.try(:[], :ranges)
    ranges_select_values = params.try(:[], :ranges_select)

    if !ranges_values.nil?
      elems = []
      ranges_values.each do |p|
        values = p[1].split(',').map(&:to_i)
        elems << @category.properties.find(p[0].to_i).list_items.select {|l| l.title.to_i >= values[0] && l.title.to_i <= values[1]}.map(&:id).map(&:to_s) if values.size == 2
      end
      param_lists << elems
      param_lists = param_lists.flatten
    end

    if !ranges_select_values.nil?
      elems = []
      values = []
      ranges_select_values.each do |p|

        if p[1][0] != ""
          values[0] = ListItem.find(p[1][0].to_i).title.to_i
        else
          values[0] = @category.properties.find(p[0]).list_items.first.title.to_i
        end

        if p[1][1] != ""
          values[1] = ListItem.find(p[1][1].to_i).title.to_i
        else
          values[1] = @category.properties.find(p[0]).list_items.last.title.to_i
        end

        values.sort!
        elems << @category.properties.find(p[0].to_i).list_items.select {|l| l.title.to_i >= values[0] && l.title.to_i <= values[1]}.map(&:id).map(&:to_s) if values.size == 2
      end
      param_lists << elems
      param_lists = param_lists.flatten
    end

    {
      list_items: param_lists,
      hierarch_list_items: params.try(:[], :hierarch_list_items),
      category_id: @category.id,
      page: params[:page]
    }
  end
end

app/controllers/metadata/categories_controller.rb
class Metadata::CategoriesController < Metadata::ApplicationController
  before_action :find_category, only: [:show, :edit, :destroy]

  def index
    @categories = Category.roots.ordered
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      render partial: 'children', locals: { category: @category.parent } and return if request.xhr?

      respond_with @category, location: -> { [:metadata, @category] }
    else
      render :new and return
    end
  end

  def edit
  end

  def show
  end

  def update
    if @category.update(category_params)
      render partial: 'children', locals: { category: @category.parent } and return if request.xhr?

      respond_with @category, location: -> { [:metadata, @category] }
    else
      render :edit and return
    end
  end

  def add_existed
    @category = Category.find(params[:category_id])
    @categories = Category.roots.ordered
  end

  def remove_link
    Category.find(params[:category_id]).update_column(:connect_with_id,  nil)

    render partial: 'children', locals: { category: Category.find(params[:parent_id]) } and return
  end

  def destroy
    if @category.parent
      @parent = @category.parent
      @category.destroy
      render partial: 'children', locals: { category: @parent } and return if request.xhr?
    else
      @category.destroy
      redirect_to metadata_categories_path
    end
  end

  def update_category_property_position
    CategoryProperty.find(params[:category_property_id]).update_attribute :row_order_position, params[:row_order]

    render nothing: true and return
  end

  private
  def category_params
    params.require(:category).permit(:title, :parent_id, property_ids: [], link_ids: [])
  end

  def find_category
    @category = Category.find(params[:id])
  end
end

app/helpers/categories_helper.rb
# == Schema Information
#
# Table name: categories
#
#  id              :integer          not null, primary key
#  title           :string
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  ancestry        :string
#  ancestry_depth  :integer          default(0)
#  connect_with_id :integer
#

module CategoriesHelper
  def min_value(property)
    property.list_items.map(&:title).map(&:to_i).delete_if {|x| x == 0}.min
  end
  def max_value(property)
    property.list_items.map(&:title).map(&:to_i).max
  end
  def ticks_value(property)
    property.list_items.map(&:title).map(&:to_i).delete_if{|x| x == 0}.sort.each_slice(property.list_items.count/4).map(&:first)
  end
  def value(property_id, params_ranges)
    if !params_ranges.nil?
      params_ranges.find {|p| p[0].to_i == property_id}[1].split(',').map(&:to_i)
    else
      property = Property.find(property_id)
      return [min_value(property),max_value(property)]
    end
  end
  def selected_for_ranges_select(params_ranges_select, property, position)
    if !params_ranges_select.try(:[], "#{property.id.to_s}").nil?
      params_ranges_select[property.id.to_s][position == 'first' ? 0 : 1]
    end
  end
end

app/helpers/metadata/categories_helper.rb
module Metadata::CategoriesHelper
  def recursive_children(node)
    return '' unless node.inserted.present?

    # FIXME: странно, но с нормальными content_tag сходу не заработало. пока так, надо переписать

    content = '<ul class="js-can-hidden can-hidden">'
    node.inserted.each do |child|
      content << "<li>#{link_to child, metadata_category_category_path(node, child)}"
      content << "<span class='glyphicon glyphicon-plus js-handle-hidden'></span>" if child.inserted.present?

      content << recursive_children(child) if child.inserted.present?
      content << "</li>"
    end
    content << '</ul>'

    content.html_safe
  end

  def define_remote(params)
    if params[:remote].present?
      params[:remote] == 'true' ? true : false

      return
    end

    true
  end
end

app/views/categories/_hierarch_inputs.html.haml
- parent = params.try(:[], 'hierarch_list_item_parents')
= f.input :hierarch_list_item_parents,
  label: false,
  input_html: {class: 'js-get-list-items-parent', name: 'hierarch_list_item_parents[]'},
  collection: property.hierarch_list_items,
  selected: parent,
  :include_blank => true

= f.input :hierarch_list_items,
  input_html: {class: 'js-get-list-items-children', name: 'hierarch_list_items[]'},
  label: false,
  collection: params[:hierarch_list_items].try(:[], hierarch_counter) ? HierarchListItem.find(params.try(:[], 'hierarch_list_items')[hierarch_counter]).parent.children : [],
  selected: params.try(:[], 'hierarch_list_items')

app/views/categories/_range_buttons_inputs.html.haml
.js-range-buttons
  = f.input :list_items,
    label: false,
    input_html: {name: 'list_items[]'},
    collection: property.list_items,
    checked: params.try(:[], 'list_items'),
    as: 'check_boxes'

app/views/categories/_range_inputs.html.haml
= f.input :range_values,
  label: false,
  input_html: {class: 'js-slider', name: "ranges[#{property.id}]",
    data: {min: min_value(property),
      value: value(property.id, params['ranges']),
      max: max_value(property),
      ticks: ticks_value(property),
      ticks_labels: ticks_value(property)}}

app/views/categories/_range_select_inputs.html.haml
= f.input :range_select_values,
  label: false,
  include_blank: true,
  input_html: {name: "ranges_select[#{property.id}][]"},
  selected: selected_for_ranges_select(params['ranges_select'], property, 'first'),
  collection: property.list_items

= f.input :range_select_values,
  label: false,
  include_blank: true,
  input_html: {name: "ranges_select[#{property.id}][]"},
  selected: selected_for_ranges_select(params['ranges_select'], property, 'last'),
  collection: property.list_items

app/views/categories/_standart_inputs.html.haml
- property.update_attribute(:show_on_filter_as, 'select') if property.show_on_filter_as.nil?
= f.input :list_items,
  label: false,
  input_html: {name: 'list_items[]'},
  as: property.show_on_filter_as,
  multiple: property.show_on_filter_as == :multiselect ? true : false,
  collection: property.list_items,
  checked: params.try(:[], 'list_items'),
  selected: params.try(:[], 'list_items'),
  include_blank: true

app/views/categories/index.html.haml
%h4= 'Категории'
- @categories.each do |category|
  = link_to category.title + ' (' + category.subtree.map(&:adverts).flatten.size.to_s + ')', category_path(category)
  = '|'

app/views/categories/show.html.haml
%p= render_breadcrumbs

%h3= @category
- hierarch_counter = 0
- unless @category.inserted.present?
  .row
    .col-xs-12
      = simple_form_for :search, url: category_path(@category), method: :get do |f|
        .row
          %ul
            - if @category.all_properties.any?
              .col-xs-2
                - @category.all_properties.each do |property|
                  %li
                    %h4= property
                    - if property.show_on_filter_as == 'range'
                      = render partial: 'range_inputs', locals: {:f => f, :property => property, :params => params}
                    - if property.show_on_filter_as == 'range_select'
                      = render partial: 'range_select_inputs', locals: {:f => f, :property => property, :params => params}
                    - if property.show_on_filter_as == 'range_buttons'
                      = render partial: 'range_buttons_inputs', locals: {:f => f, :property => property, :params => params}
                    - elsif property.kind == 'hierarch_limited_list'
                      = render partial: 'hierarch_inputs', locals: {:f => f, :property => property, :params => params, :hierarch_counter => hierarch_counter}
                      - hierarch_counter+=1
                    - elsif ['select', 'check_boxes', 'radio_buttons', 'range_buttons', nil].include? property.show_on_filter_as
                      = render partial: 'standart_inputs', locals: {:f => f, :property => property, :params => params}
        = f.submit 'Search'

- if @category.inserted.present?
  - @category.inserted.each do |child|
    = link_to child.title + ' (' + child.subtree.map(&:adverts).flatten.size.to_s + ')', category_path(child)
- else
  %ul
  = paginate @adverts
  - @adverts.each do |advert|
    %li= link_to advert.title, advert_path(advert)
  = paginate @adverts